[package]
name = "SafeMathGen"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = "1.20.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[build-dependencies]
glob = "0.3.1"
copy_to_output = "2.2.0"
